<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Module
 * @package App\Models
 *
 * @property int id
 * @property int course_id
 * @property int position
 * @property string name
 */
class Module extends Model
{
    use SoftDeletes;

    public const TABLE = "modules";

    /**
     * @var string
     */
    protected $table = self::TABLE;

    /**
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (Module $module) {
            $module->position = self::query()->where('course_id', $module->course_id)->max('position') + 1;
        });
    }

    /**
     * @return Model|\Illuminate\Database\Eloquent\Relations\BelongsTo|null|object|Course
     */
    public function course()
    {
        return $this->belongsTo('App\Models\Course', 'course_id', 'id')->first();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Collection|Lesson[]
     */
    public function lessons()
    {
        return $this->hasMany("App\Models\Lesson", "module_id", "id")->get();
    }
}
