<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class TextBlock
 * @package App\Models
 *
 * @property int id
 * @property int lesson_id
 * @property int position
 * @property string content
 * @property \DateTime created_at
 * @property \DateTime updated_at
 * @property \DateTime deleted_at
 */
class TextBlock extends Model
{
    use SoftDeletes;

    public const TABLE = "text_blocks";

    protected $table = self::TABLE;

    protected $fillable = [
        'position', 'content'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (TextBlock $model){
            $model->position = self::where('lesson_id', $model->lesson_id)->max('position') + 1;
        });
    }

    public function lesson()
    {
        return $this->belongsTo('App\Models\Lesson', 'lesson_id', 'id');
    }
}
